Lecture 6
fayyozbek/iTechArt-Fayyozbek-Fozilov- pull request #2
Opened 2022-12-26 08:19 UTC by fayyozbek

Fix comments, rename branch, delete unnecessary spaces

2022-12-26 11:53 UTC, AlexanderZnak requested changes
Unhandled exception. OpenQA.Selenium.DriverServiceNotFoundException: The geckodriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://github.com/mozilla/g
eckodriver/releases.
   at OpenQA.Selenium.DriverService.FindDriverServiceExecutable(String executableName, Uri downloadUrl)
   at OpenQA.Selenium.Firefox.FirefoxDriverService.CreateDefaultService()
   at OpenQA.Selenium.Firefox.FirefoxDriver.CreateService(FirefoxOptions options)
   at OpenQA.Selenium.Firefox.FirefoxDriver..ctor(FirefoxOptions options)
   at Program.Main(String[] arg) in C:\Users\Aliaksandr.Znak\RiderProjects\iTechArt-Fayyozbek-Fozilov-\Homework_QA_Automation\Program.cs:line 6

I did not manage to run your homework

2022-12-26 12:38 UTC, fayyozbek commented
You cannot run my homework, cause you don't have necessary driver for firefox. So I change the browser from firefox  to chrome.

2022-12-28 11:41 UTC, TanyaBorisenko requested changes

2022-12-28 11:41 UTC, TanyaBorisenko commented on Lecture_6/Lecture_6.cs
> +class Program{
space

2022-12-28 11:41 UTC, TanyaBorisenko commented on Lecture_6/Lecture_6.cs
> +﻿
remove space

2022-12-28 11:41 UTC, TanyaBorisenko commented on Lecture_6/Lecture_6.cs
> +    public void Test(){
space

2022-12-28 11:41 UTC, TanyaBorisenko commented on Lecture_6/Lecture_6.cs
> +       element= driver.FindElement(By.XPath("//h4[text()='Graphic Design']"));// looking for h4 which text equal to "Graphic Design"
space

2022-12-28 11:41 UTC, TanyaBorisenko commented on Lecture_6/Lecture_6.cs
> +       IWebElement element= driver.FindElement(By.XPath("//a[contains(@href, '/services/marketing-tools/')]"));// looking for hyperlink which href contains the link to marketing tools
space

2022-12-28 11:41 UTC, TanyaBorisenko commented on Lecture_6/Lecture_6.cs
> +       driver.Url="https://uzmarketing.com/";// move to website by link
space

2022-12-28 16:24 UTC, closed without merging